// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebarsAvaliacoesClinicas = {
  avaliacoesClinicasSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebarsAvaliacoesClinicas;