// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebarsPraticaClinica = {
  praticaClinicaSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebarsPraticaClinica;