// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebarsGestaoConsultorio = {
  gestaoConsultorioSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebarsGestaoConsultorio;